#!/usr/bin/env bash
#install ufw(Ubuntu firewall)
#specify a rule that blocks all incoming traffic
#allow listening on specific ports

sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
