#!/usr/bin/bash
#instal and rin apache server

sudo apt-get update
sudo apt-get -y install apache2
sudo service apache2 start
sudo apt-get -y install ufw
sudo ufw app list
sudo ufw allow "Hello Holberton"
echo "my job" > /var/www/html/index.html
